#!/bin/sh
ssh ubuntu@43.201.52.36 <<EOF
    cd ~/api-test		
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 18.19.1
    npm install
    npm install -g pm2
    pm2 restart app.js
    exit
EOF