#!/bin/sh
ssh ubuntu@3.25.181.51 <<EOF
    cd ~/seoul_cultural_event
    git pull origin master
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    . ~/.nvm/nvm.sh 
    nvm install 20.11.1
    npm install
    npm install -g pm2
    sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 3000
    pm2 restart ecosystem.config.js
    exit
EOF

